### ISSUE TITLE
Trying to access the cheats menu result in exception on Atmospshere 17 and FW 11.0.1

### ISSUE THREAD

**Issue by shalien** [FlagBrew/Checkpoint#388] opened 2021-01-07 08:40 UTC
**Describe the bug**
The console will crash to exception when pressing R to access cheats menu
Tested in both  CFW sysNAND and CFW emuNAND

**To Reproduce**
1. Launch CFW using Atmosphere fusée-primary 
2. Launch the homebrew menu on an application
3. Launch Checkpoint
4. Choose a game (Tested on Zelda: BoTH, Pokemon Sword and TWEWY)
5. Press R to access cheat menu

**Expected behavior**
Cheat menu should be displayed

**Screenshots**
Will provide them later

**Switch:**
- Entrypoint: Application take over
- System version: 11.0.1
- Checkpoint version: 3.7.4
- SD Card Filesystem: FAT32
- Result code (if available):

**Additional context**

**Comment by GriffinG1** [comment] 2021-01-07 08:43
Duplicate of #244 i believe

**Closed** 2021-11-13 09:43 UTC
