### ISSUE TITLE
Backups Not Showing On MicroSD Card

### ISSUE THREAD

**Issue by chrisnieves4075** [FlagBrew/Checkpoint#295] opened 2019-12-18 17:43 UTC
I open up checkpoint using the hold R and press A and keep holding A. When i make a back up of pokemon sword it says successful saved to sd card. I make another back up to edit using PKHEX and get the same successful saved to sd card. So when i close out checkpoint turn off console and remove microsd card. I connect to my labtop and i go into the switch folder,  the checkpoint folder and finally the pokemon sword folder but i can see the folder checkpoint created but with no save file inside. Any help to fix this. Im running atmosphere lastest version.

**Comment by jd00bz** [comment] 2020-02-28 22:09
If you have any valid backups on your sd card, back them up on your pc. Then delete every directory in the “saves” folder as well as checkpoint.log and config.json. Open checkpoint again and it will create a new log and json. back up a save. If the backup appears below “new” after you created it, proceed as I shall mention below. If not, you may be experiencing a different issue. 

If the new save is appearing, create a new backup in checkpoint for every backup file you want to have. Copying your old backup folders to the directory will not work for this. Instead, checkpoint has to make the folder, and then you will need to manually overwrite the savedata.bin file with your old backup. Once the old backup file is in the new folder that checkpoint created, it can be restored in checkpoint.

**Comment by GriffinG1** [comment] 2021-11-14 08:59
I'm marking this as failed to reproduce as plenty of people have been able to backup their SwSh saves via Checkpoint in the nearly two years since this was opened.

**Closed by GriffinG1** 2021-11-14 08:59 UTC
Labels: bug, switch, failed to reproduce
