### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by armon222** [FlagBrew/Checkpoint#331] opened 2020-03-25 16:22 UTC
I am on both the latest version of switch firmware as well as checkpoint, but for some reason, ACNH does not show up in checkpoint.

**Comment by piepie62** [comment] 2020-03-25 16:23
Duplicate of #324

**Closed by piepie62** 2020-03-25 16:23 UTC

**Comment by armon222** [comment] 2020-03-25 16:24
wait no, i am not requesting a feature. I am saying that ACNH is not even showing up in checkpoint for me.

**Comment by piepie62** [comment] 2020-03-25 16:25
It's the same problem. The issue is that the save type is not yet supported

**Comment by armon222** [comment] 2020-03-25 16:25
Oh ok, thank you I was unaware of this
