### ISSUE TITLE
Restoring savegames doesn't work. All old savegame backups say 0:00 hours playtime.

### ISSUE THREAD

**Issue by Pyjamaa** [FlagBrew/Checkpoint#345] opened 2020-04-27 16:32 UTC
**Describe the bug**
Restoring save games doesn't work.
I can see my savegame backups in the list of the games when I click restore, it says it was restored successfully. But when I load the game it's still the old savegame.

Also when I hover over the backups of my savegames it says "0:00 Hours playtime"
Seems like it can't probably read my backups?

**To Reproduce**
1. Go to Checkpoint
2. Click on any game
3. Scroll down to your backups and click restore

**Expected behavior**
Restore my old save game.

**Screenshots**
https://imgur.com/a/CnSZcUS

**Switch:**
- Entrypoint:
- System version: 9.2.0
- Checkpoint version: 3.7.4
- SD Card Filesystem: FAT32

**Additional context**
I remember I already restored savegames on FW 8.1.0. And it worked perfectly.
So my backups should be good.
Seems like it has something to do with the new FW/Version?

**Comment by BernardoGiordano** [comment] 2020-04-27 16:44
No help can be provided if you don't state *exactly* the error you're getting. Provide the error code soon, otherwise I'll close this issue since it contains no useful information.

**Comment by Pyjamaa** [comment] 2020-04-27 16:54
There is no error code.
My problem is:
I launch Checkpoint.
I select a game.
I choose an old backup of a savegame from the game I want to restore.
I click on restore.
It says it was restored successfully. 
I load the game and it still has the old savegame not the one I just restored with Checkpoint.

A thing I noticed, it says I have 0 hours playtime on my old backups.
Which is wrong.

**Comment by BernardoGiordano** [comment] 2020-04-27 17:01
Did you format your switch? Are you using emunand? Where did you play the games?

**Comment by Pyjamaa** [comment] 2020-04-27 17:09
No I didn't format the Switch.
But I made a new emunand after I backuped my savegames when I was still on 8.1.0. Could this be the problem?

Yes I'm using Atmos with emuNand 9.2.0
I play the games on the Atmos emunand.

**Comment by PP-theSLAYER** [comment] 2020-04-29 19:59
Are you trying to restore saves into your sysNAND, using Checkpoint on emuNAND?

**Comment by Pyjamaa** [comment] 2020-04-30 16:44
No, the savegame backups are from my old emunand.
I had to create a new emunand.
And now I'm trying to restore my savegames from the old one in my new emunand.

**Comment by alexnovelli-meudna** [comment] 2020-05-27 16:54
Same problem here.
I use SX OS (2.9.5) with Emunand (10.0.2). I made a backup for all my saves and delete old Emunand to make a new one. The message says successfully restored but when I open the game (Zelda Link's Awakening), the save is not there.
I tried Atmosphere and the problem is the same.
Help please!

**Comment by alexnovelli** [comment] 2020-05-27 16:56
Same problem here.

I use SX OS (2.9.5) with Emunand (10.0.2).
I made a backup for all my saves and delete old Emunand to make a new one.
The message says successfully restored but when I open the game (Zelda Link's Awakening), the save is not there.

I'm using FAT32 but during backups the SD Card was in ExFAT.

I tried Atmosphere and the problem is the same.

Help please!

**Comment by alexnovelli-meudna** [comment] 2020-05-27 17:03
Note: I've searched for the playtime information here, but it not even show. The information finish in User.

**Comment by GriffinG1** [comment] 2020-05-27 21:39
@alexnovelli SXOS is in no way supported by FlagBrew. Switch to atmosphere and test again.

**Comment by alexnovelli** [comment] 2020-05-27 21:45
As I already mencioned, I've tested in Atmosphere with the same results.

**Comment by alexnovelli** [comment] 2020-05-28 22:13
![2020-05-28 19 09 52](https://user-images.githubusercontent.com/7763832/83199264-3db7d900-a117-11ea-9b98-ae1afcaabecf.jpg)

**Closed** 2021-11-13 09:47 UTC
