### ISSUE TITLE
[switch] Switching between users doesn't change the user the backups are made from

### ISSUE THREAD

**Issue by ImanolBarba** [FlagBrew/Checkpoint#466] opened 2022-09-02 14:10 UTC
- Checkpoint ver: 3.8.0 (happened on SciresM's fork for 3.7.5 too, but it didn't happen for 3.7.4 as far as I remember)
- Device: Nintendo Switch unpatched Erista unit
- OS: HOS 14.1.2 (happened on 12.0.3 too)
- CFW: Atmosphere 1.3.2, running on EmuNAND
- Bootloader: hekate 5.8.0

Description of the issue
--
I'm trying to make backups of savegames on a switch with two users, let's call them A and B.

Irregardless of how I launch Checkpoint, it starts with user A, changing the active user with ZL/ZR to user B changes the list of games on the left to reflect those that user B has savegames present. But if I try to make a New backup, it tries to do it from user A. This is inferred as the backup name contains A's username.

I can also see that in the details of the title (the bit on top that lists Title ID, Author, etc, *always* shows A's username, and the picture and username in the lower right is always from User A, irregardless of how much I try to change to user B.

Repro
--
1. Launch CFW
2. Launch hbmenu in non-applet mode (Checkpoint refuses to start in applet mode). It's irrevelant whether I choose user A or B when the user selection pops up when launch a game with R pressed, bug is still present
3. Launch Checkpoint. At this point, user A is the selected user both in the list of games shown and in the lower right picture and name
4. Press ZL/ZR to change user (also can be done by tapping the user picture) and change to user B
5. At this point, user A picture still shows, and on top it shows `User: UserA`.
6. Select any game
7. Select `New...`
8. Dialog pops up showing `20220902-160654 UserA`, clearly showing it's backing up User A's save, not B

Expected Behaviour
--
- As soon as I change the user to user B, it should show `User: UserB` on top, as well as user B's profile picture and name in the bottom
- When doing a new backup, it should be of the newly changed user.

Thanks

**Comment by ImanolBarba** [comment] 2022-09-02 15:26
Nothing interesting in checkpoint.log besides:

```
[2022-09-02 15:19:51] [ INFO] FTP Server failed to load. Result code 0xFFFFFFFF.
```

Which is unrelated and normal since it's in airplane mode

**Comment by ImanolBarba** [comment] 2022-09-02 15:27
config.json:

```
{
  "additional_save_folders": {},
  "favorites": [],
  "filter": [],
  "ftp-enabled": false,
  "pksm-bridge": false,
  "version": 4
}
```

**Comment by GriffinG1** [comment] 2022-09-02 15:31
Duplicate of #440. Please move there.

**Closed by GriffinG1** 2022-09-02 15:31 UTC
