### ISSUE TITLE
File folder unable to be found.

### ISSUE THREAD

**Issue by Gevlyn507** [FlagBrew/Checkpoint#309] opened 2020-01-21 15:00 UTC
When putting my sd card into my computer, the folder containing the game saves appears to not exist in the location it's listed as. 
The folder cannot be coppied, moved, and files inside cannot be accessed.
I am using the latest version of checkpoint.

![20200121_010642](https://user-images.githubusercontent.com/60144121/72815245-f7fc7880-3c2b-11ea-9a94-4c34bc9fa708.jpg)
![20200121_000712](https://user-images.githubusercontent.com/60144121/72815277-06e32b00-3c2c-11ea-841a-7263cb551e7f.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**3DS:**
- Entrypoint:
- System version:
- Checkpoint version:
- Result code (if available):

**Switch:**
- Entrypoint:
- System version:
- Checkpoint version:
- SD Card Filesystem:
- Result code (if available):

**Additional context**

**Comment by deadair3210** [comment] 2020-01-21 16:48
One, use the template please
Two, it's likely because the filepath is too long, as to a fix that would agree with checkpoint, idk

**Comment by Gevlyn507** [comment] 2020-01-21 17:34
Sorry about the template, first post on github and I'll master the nuances in time. That being said I went through the identical steps of this process before with no issues. Checkpoint > extract save > put save file on computer as a backup. I agree the filepath is long but am I able to edit the name of the folder inside checkpoint? The major issue is once I'm trying to access the folder from my computer it treats it like it's just not there.

**Comment by BernardoGiordano** [comment] 2020-01-26 08:34
It doesn't seem to be that long. This could be caused by special characters in your nickname, actually. What's you nickname on the switch?

**Comment by GriffinG1** [comment] 2021-11-14 08:51
Requested info not provided in almost two years, closing...

**Closed by GriffinG1** 2021-11-14 08:51 UTC
Labels: bug, switch
