### ISSUE TITLE
chcek point doesn't start.

### ISSUE THREAD

**Issue by glvaleri** [FlagBrew/Checkpoint#460] opened 2022-05-22 13:33 UTC
I can't load check point, I have tried holding R and then loading and still can't get it to load.

Please help..

Thanks in advance.

G. Valeri

**Comment by GriffinG1** [comment] 2022-05-23 07:26
> I have tried holding R and then loading
Can you please elaborate? What did you try loading while holding R?

**Comment by glvaleri** [comment] 2022-05-23 12:23
Checkpoint is not starting for me on my swtich, there is a post about the issue (see below) that states if checkpoint doesn't start   hold down "R" and then launch check point, I did that and check point still does not run.


Hi! If this is happening, you are likely attempting to launch Checkpoint via applet mode (launching the album).

As of 3.8.0, Checkpoint officially no longer supports launching in applet mode due to the decreased amount of available memory in applet mode. This prevents stuff like the keyboard being usable.

If you would like to launch Checkpoint again, please use Atmosphere's* Title Takeover feature, which is done by launching a game while holding R.

**Comment by BernardoGiordano** [comment] 2022-05-23 12:25
That still doesn't help. Which Checkpoint version are you trying to start? Can you give us information about your system/OS/CFW? Can you make a video where you show the full process?

**Comment by GriffinG1** [comment] 2022-05-23 12:27
My post that you are copying clearly says to launch **a game** while holding R, not checkpoint. Stop using applet mode.

Duplicate of #450

**Closed by GriffinG1** 2022-05-23 12:27 UTC

**Comment by glvaleri** [comment] 2022-05-23 12:30
i missunderstood the post...

Thanks for the clarification.
