### ISSUE TITLE
Bug Report - ARM 11 Crash when exiting and closing via Home + X

### ISSUE THREAD

**Issue by JasonCubed132** [FlagBrew/Checkpoint#299] opened 2020-01-01 21:06 UTC
**Describe the bug**
ARM11 Crash when exiting Checkpoint 3.7.2 via the Home button and then X while it's populating the title list.

**To Reproduce**
1. Open Checkpoint
2. Cause the title list to reload via any method.
3. Before it has finished, press HOME and then X.
4. You will be greeted with an ARM 11 crash

**Expected behavior**
Checkpoint should close normally.

**Screenshots**
[crash_dump_00000004.zip](https://github.com/FlagBrew/Checkpoint/files/4014531/crash_dump_00000004.zip)

**3DS:**
- Entrypoint: B9S 1.3 Luma 10.0.1
- System version: 11.13.0-45E
- Checkpoint version: 3.7.2
- Result code (if available): None

**Additional context**
Issue originally opened on the Luma3DS repo [here](https://github.com/AuroraWright/Luma3DS/issues/1356) and moved to here since it appears to be an issue with Checkpoint

My own testing can only reproduce this during repopulating the titles list, so I have listed this issue as such. However, the original person who opened the issue on the Luma3DS repo has not specified whether it was still reloading at the time.

**Comment by GriffinG1** [comment] 2020-01-01 21:26
You’re not using the latest version.

**Comment by JasonCubed132** [comment] 2020-01-01 21:34
Same crash with 3.7.4

**Comment by GriffinG1** [comment] 2020-01-01 21:38
The other thing is, of course it’s going to crash if you close it while it’s doing an operation.

**Comment by JasonCubed132** [comment] 2020-01-01 21:40
That's fair, but is it an operation exception that could be caught and contained without an Arm 11 crash?

**Comment by Oreo639** [comment] 2020-01-01 21:49
It is possible to block exiting to the home menu in libctru now.
PKSM does this.

**Comment by GriffinG1** [comment] 2020-01-01 21:51
I’m gonna guess no for catching it, considering you’re trying to exit the application at the same time which would be handled on Luma’s side.

Easiest solution is to just not do dumb stuff like close checkpoint while it’s doing an operation '_>'

**Comment by JasonCubed132** [comment] 2020-01-03 23:34
Original person who reported the issue on Luma3DS has said it occured after they were done loading.

**Comment by GriffinG1** [comment] 2020-01-04 00:07
I cannot reproduce. Please ensure that the loading is completely finished (checkpoint will sort them alphabetically afterwards) and test again.

**Comment by GriffinG1** [comment] 2020-01-04 00:08
In addition, @1031982 please move here.

**Comment by 1031982** [comment] 2020-01-04 02:29
I am beginning to think that it was a random crash that can't be reproduced or maybe something with the microsd card or slot. I haven't been able to reproduce the crash either.

**Comment by GriffinG1** [comment] 2021-11-14 08:56
I can only reproduce this while closing it in the middle of a refresh, which as I said last year: you shouldn't be closing things during an operation. My only suggestion is the one Oreo gave, that home menu be blocked off while titles are being loaded/refreshed. cc @BernardoGiordano and @LiquidFenrir for implementation.

**Closed by GriffinG1** 2021-11-14 08:56 UTC
Labels: bug, 3ds, failed to reproduce
